// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEmqmJUdkRla2Pm6Ows4dvzrS30XfoBk',
    appId: '1:606163209688:web:7979ad1a60d6c47ea636ad',
    messagingSenderId: '606163209688',
    projectId: 'sync-queue',
    authDomain: 'sync-queue.firebaseapp.com',
    storageBucket: 'sync-queue.firebasestorage.app',
    measurementId: 'G-1NHRBHKR47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuC0HHthqEKbh67Et3oytKpjVFnw3dAA',
    appId: '1:606163209688:android:78711662f70bcbfea636ad',
    messagingSenderId: '606163209688',
    projectId: 'sync-queue',
    storageBucket: 'sync-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDYHvIIEvUBNaXOl4Jb5rTKMcI0BVYxQ',
    appId: '1:606163209688:ios:bdc15e31afe0c9faa636ad',
    messagingSenderId: '606163209688',
    projectId: 'sync-queue',
    storageBucket: 'sync-queue.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstSyncQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDYHvIIEvUBNaXOl4Jb5rTKMcI0BVYxQ',
    appId: '1:606163209688:ios:bdc15e31afe0c9faa636ad',
    messagingSenderId: '606163209688',
    projectId: 'sync-queue',
    storageBucket: 'sync-queue.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstSyncQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUEmqmJUdkRla2Pm6Ows4dvzrS30XfoBk',
    appId: '1:606163209688:web:c92125da438c91eda636ad',
    messagingSenderId: '606163209688',
    projectId: 'sync-queue',
    authDomain: 'sync-queue.firebaseapp.com',
    storageBucket: 'sync-queue.firebasestorage.app',
    measurementId: 'G-N77LVXQET0',
  );
}
